/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as AdminTokenValidatorRouteImport } from './routes/admin/token-validator'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminGenderRouteImport } from './routes/admin/gender'
import { Route as AdminAliasesRouteImport } from './routes/admin/aliases'

const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTokenValidatorRoute = AdminTokenValidatorRouteImport.update({
  id: '/admin/token-validator',
  path: '/admin/token-validator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGenderRoute = AdminGenderRouteImport.update({
  id: '/admin/gender',
  path: '/admin/gender',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAliasesRoute = AdminAliasesRouteImport.update({
  id: '/admin/aliases',
  path: '/admin/aliases',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guest': typeof GuestRoute
  '/admin/aliases': typeof AdminAliasesRoute
  '/admin/gender': typeof AdminGenderRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/token-validator': typeof AdminTokenValidatorRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guest': typeof GuestRoute
  '/admin/aliases': typeof AdminAliasesRoute
  '/admin/gender': typeof AdminGenderRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/token-validator': typeof AdminTokenValidatorRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guest': typeof GuestRoute
  '/admin/aliases': typeof AdminAliasesRoute
  '/admin/gender': typeof AdminGenderRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/token-validator': typeof AdminTokenValidatorRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guest'
    | '/admin/aliases'
    | '/admin/gender'
    | '/admin/members'
    | '/admin/token-validator'
    | '/sessions/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guest'
    | '/admin/aliases'
    | '/admin/gender'
    | '/admin/members'
    | '/admin/token-validator'
    | '/sessions/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/guest'
    | '/admin/aliases'
    | '/admin/gender'
    | '/admin/members'
    | '/admin/token-validator'
    | '/sessions/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestRoute: typeof GuestRoute
  AdminAliasesRoute: typeof AdminAliasesRoute
  AdminGenderRoute: typeof AdminGenderRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminTokenValidatorRoute: typeof AdminTokenValidatorRoute
  SessionsIdRoute: typeof SessionsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/token-validator': {
      id: '/admin/token-validator'
      path: '/admin/token-validator'
      fullPath: '/admin/token-validator'
      preLoaderRoute: typeof AdminTokenValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gender': {
      id: '/admin/gender'
      path: '/admin/gender'
      fullPath: '/admin/gender'
      preLoaderRoute: typeof AdminGenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/aliases': {
      id: '/admin/aliases'
      path: '/admin/aliases'
      fullPath: '/admin/aliases'
      preLoaderRoute: typeof AdminAliasesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestRoute: GuestRoute,
  AdminAliasesRoute: AdminAliasesRoute,
  AdminGenderRoute: AdminGenderRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminTokenValidatorRoute: AdminTokenValidatorRoute,
  SessionsIdRoute: SessionsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
